### ISSUE TITLE
Extract `org.terasology.milling` in separate module

### ISSUE THREAD

**Issue by DarkWeird** [Terasology/StoneCrafting#7]
Duplication with `org.terasology.mill` in `WoodAndStone` module

see https://github.com/Terasology/WoodAndStone/issues/59

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
